name: Python CI_test
on:
  schedule:
    # 每天凌晨7点执行
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
        python -m pip install datetime
    - name: Run Python script
      run: python my_script.py
